#   BASE_IMAGE_VERSION="$(curl https://builds.coreos.fedoraproject.org/streams/stable.json --silent | jq -r '.architectures.x86_64.artifacts.metal.release')"
ARG BASE_IMAGE_VERSION
#   KERNEL_VERSION="$(podman run --rm --rmi --entrypoint /bin/rpm quay.io/fedora/fedora-coreos:$BASE_IMAGE_VERSION --query --all --queryformat '%{VERSION}-%{RELEASE}' kernel)"
ARG KERNEL_VERSION
#   ZFS_VERSION="$(URL="$(curl --head https://github.com/openzfs/zfs/releases/latest --output /dev/null --silent --write-out '%{redirect_url}')"; printf '%s' "${URL##*zfs-}")"
ARG ZFS_VERSION

FROM ghcr.io/ublue-os/akmods-zfs:coreos-stable-${BASE_IMAGE_VERSION%%.*}-$KERNEL_VERSION AS akmods-zfs


FROM quay.io/fedora/fedora-coreos:$BASE_IMAGE_VERSION
ARG KERNEL_VERSION
ARG ZFS_VERSION

RUN --mount=type=tmpfs,target=/tmp \
    --mount=type=bind,from=akmods-zfs,source="/rpms",target="/tmp/rpms",rw \
    [ "$(/bin/rpm --query --all --queryformat '%{VERSION}-%{RELEASE}' kernel)" = "$KERNEL_VERSION" ] \
 && [ -n "$(find /tmp/rpms/kmods/zfs -name "zfs-${ZFS_VERSION}-*.rpm" -print -quit)" ] \
 && rm --verbose --force \
      /tmp/rpms/kmods/zfs/other/zfs-test-*.rpm \
 && rpm-ostree install -y \
      /tmp/rpms/ucore/*.rpm \
      /tmp/rpms/kmods/zfs/*.rpm \
      /tmp/rpms/kmods/zfs/other/*.rpm \
 && depmod -a "$(rpm --query --all --queryformat '%{VERSION}-%{RELEASE}.%{ARCH}' kernel)" \
 && printf 'zfs\n' >/etc/modules-load.d/zfs.conf \
 && rm --recursive \
      /var/cache \
      /var/lib/pcp \
      /var/log \
 && ostree container commit
