#   BASE_IMAGE_VERSION="$(curl https://builds.coreos.fedoraproject.org/streams/stable.json --silent | jq -r '.architectures.x86_64.artifacts.metal.release')"
ARG BASE_IMAGE_VERSION
ARG PARENT_IMAGE=quay.io/fedora/fedora-coreos:$BASE_IMAGE_VERSION

FROM $PARENT_IMAGE

RUN rpm-ostree install -y tmux \
 && rm --recursive \
      /var/cache \
 && ostree container commit
